# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: krystof2-ops.FinderWin
PackageVersion: 1.4.0
InstallerType: nullsoft
Scope: user
InstallModes:
- interactive
- silent
UpgradeBehavior: install
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/krystof2-ops/finder-win/releases/download/v1.4.0/Finder-Win_1.4.0_x64-setup.exe
  InstallerSha256: CE56F5C63E99259B3DB52B992EE598831220DBD1E29F4D0145F4F8A84BB95621
ManifestType: installer
ManifestVersion: 1.6.0
